version: 2
jobs:
  # dependencies: 
  #   pre:
      #- sudo apt-get update
      #- sudo apt-get install sshpass

  steps:
    - run: echo $USERNAME $PASSWORD

  # deployment:
  #     production:
  #         branch: master
  #         commands:
          #- sshpass -p $PASSWORD scp -rvC ./ ramr@cardinal.stanford.edu:WWW