version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.3.1
  # dependencies: 
  #   pre:
      #- sudo apt-get update
      #- sudo apt-get install sshpass

  steps:
    - checkout
    - run: echo $USERNAME $PASSWORD

  # deployment:
  #     production:
  #         branch: master
  #         commands:
          #- sshpass -p $PASSWORD scp -rvC ./ ramr@cardinal.stanford.edu:WWW