version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.3.1
    steps:
      - checkout
      - run: echo $USERNAME $PASSWORD
  # dependencies: 
  #   pre:
      #- sudo apt-get update
      #- sudo apt-get install sshpass
  # deployment:
  #     production:
  #         branch: master
  #         commands:
          #- sshpass -p $PASSWORD scp -rvC ./ ramr@cardinal.stanford.edu:WWW